Необхідно виконати завдання, використовуючи  pandas dataframe, проаналізувати часові витрати на виконання процедур (профілювання часу виконання здійснити за допомогою модуля timeit).

Завдання 1:
Звантажити та відкрити (вручну або через запропонований скрипт на сайті) наступний датасет: Individual Household Electric Power Consumption Dataset

In [1]:
import pandas as pd
import timeit
import os

txt_file = "household_power_consumption.txt"

start_time = timeit.default_timer()
# Зчитуємо дані. Параметр na_values=['?'] одразу конвертує текстові знаки питання у порожні значення (NaN)
df = pd.read_csv(txt_file, sep=';', na_values=['?'], low_memory=False)

end_time = timeit.default_timer()
load_time = end_time - start_time

print(f"Початкова кількість рядків: {len(df)}")
print(f"Час зчитування файлу: {load_time:.4f}")

df.head(10)

Початкова кількість рядків: 2075259
Час зчитування файлу: 2.8932

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0
5,16/12/2006,17:29:00,3.520,0.522,235.02,15.0,0.0,2.0,17.0
6,16/12/2006,17:30:00,3.702,0.520,235.09,15.8,0.0,1.0,17.0
7,16/12/2006,17:31:00,3.700,0.520,235.22,15.8,0.0,1.0,17.0
8,16/12/2006,17:32:00,3.668,0.510,233.99,15.8,0.0,1.0,17.0
9,16/12/2006,17:33:00,3.662,0.510,233.86,15.8,0.0,2.0,16.0

Завдання 2: Здійснити data cleaning

In [2]:
# Рахуємо загальну кількість порожніх клітинок до очищення
missing_before = df.isna().sum().sum()
print(f"Знайдено порожніх клітинок (NaN) до очищення: {missing_before}")

start_time = timeit.default_timer()
# Очищення: видаляємо всі рядки, де є хоча б одне порожнє значення (NaN)
df_cleaned = df.dropna()

end_time = timeit.default_timer()
clean_time = end_time - start_time

print(f"Залишилося рядків: {len(df_cleaned)}")
print(f"Видалено рядки: {len(df) - len(df_cleaned)}")
print(f"Час виконання очищення: {clean_time:.4f}")

# Оновлюємо основний фрейм даних для подальшої роботи
df = df_cleaned

Знайдено порожніх клітинок (NaN) до очищення: 181853
Залишилося рядків: 2049280
Видалено рядки: 25979
Час виконання очищення: 0.5105

Завдання 3:
Обрати всі записи, у яких загальна активна споживана потужність перевищує 5 кВт.

In [3]:
def filter_high_power(dataframe):
    return dataframe[dataframe['Global_active_power'] > 5.0]

start_time = timeit.default_timer()

res_task3 = filter_high_power(df)

execution_time = timeit.default_timer() - start_time
print(f"Знайдено записів: {len(res_task3)}")
print(f"Час виконання: {execution_time:.4f}")
res_task3.head()

Знайдено записів: 17547
Час виконання: 0.0095

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
11,16/12/2006,17:35:00,5.412,0.470,232.78,23.2,0.0,1.0,17.0
12,16/12/2006,17:36:00,5.224,0.478,232.99,22.4,0.0,1.0,16.0

Завдання 4: Обрати всі записи, у яких сила струму лежить в межах 19-20 А, для них виявити ті, у яких пральна машина та холодильних споживають більше, ніж бойлер та кондиціонер.

In [4]:
def filter_intensity_appliances(dataframe):
    return dataframe[(dataframe['Global_intensity'] >= 19.0) & 
                     (dataframe['Global_intensity'] <= 20.0) & 
                     (dataframe['Sub_metering_2'] > dataframe['Sub_metering_3'])]

start_time = timeit.default_timer()

res_task4 = filter_intensity_appliances(df)

execution_time = timeit.default_timer() - start_time
print(f"Знайдено записів: {len(res_task4)}")
print(f"Час виконання: {execution_time:.4f}")
res_task4.head()

Знайдено записів: 2509
Час виконання: 0.0207

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
45,16/12/2006,18:09:00,4.464,0.136,234.66,19.0,0.0,37.0,16.0
460,17/12/2006,01:04:00,4.582,0.258,238.08,19.6,0.0,13.0,0.0
464,17/12/2006,01:08:00,4.618,0.104,239.61,19.6,0.0,27.0,0.0
475,17/12/2006,01:19:00,4.636,0.140,237.37,19.4,0.0,36.0,0.0
476,17/12/2006,01:20:00,4.634,0.152,237.17,19.4,0.0,35.0,0.0

Завдання 5: Обрати випадковим чином 500000 записів (без повторів елементів вибірки), для них обчислити середні величини усіх 3-х груп споживання електричної енергії

In [5]:
def get_random_sample_means(dataframe):
    sample = dataframe.sample(n=500000, replace=False, random_state=42)
    return sample[['Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']].mean()

start_time = timeit.default_timer()

res_task5 = get_random_sample_means(df)

execution_time = timeit.default_timer() - start_time
print(f"Час виконання: {execution_time:.4f}")
print("Середні значення (Вт-год):")
print(res_task5)

Час виконання: 0.2618
Середні значення (Вт-год):
Sub_metering_1    1.119258
Sub_metering_2    1.308912
Sub_metering_3    6.452950
dtype: float64

Завдання 6: Обрати ті записи, які після 18-00 споживають понад 6 кВт за хвилину в середньому, серед відібраних визначити ті, у яких основне споживання електроенергії у вказаний проміжок часу припадає на пральну машину, сушарку, холодильник та освітлення (група 2 є найбільшою), а потім обрати кожен третій результат із першої половини та кожен четвертий результат із другої половини.

In [6]:
def filter_evening_and_slice(dataframe):
    evening_data = dataframe[(dataframe['Time'] >= '18:00:00') & 
                             (dataframe['Global_active_power'] > 6.0) & 
                             (dataframe['Sub_metering_2'] > dataframe['Sub_metering_1']) & 
                             (dataframe['Sub_metering_2'] > dataframe['Sub_metering_3'])]

    half_index = len(evening_data) // 2
    first_half = evening_data.iloc[:half_index]
    second_half = evening_data.iloc[half_index:]

    res_first = first_half.iloc[::3]
    res_second = second_half.iloc[::4]

    return pd.concat([res_first, res_second])

start_time = timeit.default_timer()

res_task6 = filter_evening_and_slice(df)

execution_time = timeit.default_timer() - start_time
print(f"Фінальна кількість записів після зрізів: {len(res_task6)}")
print(f"⏱ Час виконання: {execution_time:.4f}")
res_task6.head(3)

Фінальна кількість записів після зрізів: 310
⏱ Час виконання: 0.2552

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
41,16/12/2006,18:05:00,6.052,0.192,232.93,26.2,0.0,37.0,17.0
44,16/12/2006,18:08:00,6.308,0.116,232.25,27.0,0.0,36.0,17.0
17494,28/12/2006,20:58:00,6.386,0.374,236.63,27.0,1.0,36.0,17.0

Завдання 7: Пронормувати та стандартизувати вибраний датасет

In [7]:
def scale_data(dataframe):
    numeric_cols = ['Global_active_power', 'Global_reactive_power', 'Voltage', 
                    'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']

    data_num = dataframe[numeric_cols].copy()
    
    # 1. Нормалізація: (X - min) / (max - min)
    normalized_df = (data_num - data_num.min()) / (data_num.max() - data_num.min())
    
    # 2. Стандартизація: (X - mean) / std
    standardized_df = (data_num - data_num.mean()) / data_num.std()
    
    return normalized_df, standardized_df

start_time = timeit.default_timer()

df_norm, df_stand = scale_data(df)

execution_time = timeit.default_timer() - start_time

print(f"Час виконання: {execution_time:.4f}\n")

print("Результат Нормалізації (значення від 0 до 1)")
display(df_norm.head(3))

print("\nРезультат Стандартизації (середнє = 0)")
display(df_stand.head(3))

Час виконання: 1.1590

Результат Нормалізації (значення від 0 до 1)

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,0.374796,0.300719,0.376090,0.377593,0.0,0.0125,0.548387
1,0.478363,0.313669,0.336995,0.473029,0.0,0.0125,0.516129
2,0.479631,0.358273,0.326010,0.473029,0.0,0.0250,0.548387

Результат Стандартизації (середнє = 0)

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2.955076,2.610720,-1.851816,3.098788,-0.182337,-0.051274,1.249420
1,4.037084,2.770405,-2.225274,4.133799,-0.182337,-0.051274,1.130897
2,4.050325,3.320431,-2.330213,4.133799,-0.182337,0.120487,1.249420

Завдання 8: Підрахувати коефіцієнт Пірсона та Спірмена для двох integer/real атрибутів.

In [8]:
def calculate_correlations(dataframe, col1, col2):
    # Метод Пірсона (лінійна залежність)
    pearson_corr = dataframe[col1].corr(dataframe[col2], method='pearson')
    
    # Метод Спірмена (рангова залежність)
    spearman_corr = dataframe[col1].corr(dataframe[col2], method='spearman')
    
    return pearson_corr, spearman_corr

col_a = 'Global_active_power'
col_b = 'Global_intensity'

start_time = timeit.default_timer()

pearson_res, spearman_res = calculate_correlations(df, col_a, col_b)

execution_time = timeit.default_timer() - start_time
print(f"Час виконання: {execution_time:.4f}\n")

print(f"Коефіцієнт Пірсона:  {pearson_res:.6f}")
print(f"Коефіцієнт Спірмена: {spearman_res:.6f}")

Час виконання: 2.4697

Коефіцієнт Пірсона:  0.998889
Коефіцієнт Спірмена: 0.995372

Завдання 9: Провести One Hot Encoding категоріального атрибута.

In [9]:
def perform_one_hot_encoding(dataframe):
    sample_for_encoding = dataframe.sample(5, random_state=1).copy()

    encoded_df = pd.get_dummies(sample_for_encoding, columns=['Date'])
    
    return sample_for_encoding[['Date']], encoded_df

start_time = timeit.default_timer()

original_col, result_encoded = perform_one_hot_encoding(df)

execution_time = timeit.default_timer() - start_time
print(f"Час виконання: {execution_time:.4f} секунд\n")

print("Оригінальна колонка 'Date'")
display(original_col)

print("\nРезультат після One Hot Encoding")
display(result_encoded.filter(like='Date_'))

Час виконання: 0.1393 секунд

Оригінальна колонка 'Date'

             Date
1872886  9/7/2010
732709   8/5/2008
289951   6/7/2007
288919   5/7/2007
1129172  7/2/2009

Результат після One Hot Encoding

,Date_5/7/2007,Date_6/7/2007,Date_7/2/2009,Date_8/5/2008,Date_9/7/2010
1872886,False,False,False,False,True
732709,False,False,False,True,False
289951,False,True,False,False,False
288919,True,False,False,False,False
1129172,False,False,True,False,False